In [13]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [14]:
iris_data = load_iris()  # load the iris dataset

In [16]:
print('Example data: \n' + str(iris_data.data[:5]))
print('Example labels: ' + str(iris_data.target[:5]))

x = iris_data.data
y_ = iris_data.target.reshape(-1, 1)  # Convert data to a single column

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: [0 0 0 0 0]


In [17]:
# One Hot encode the class labels with sparse output
encoder = OneHotEncoder(sparse_output=True)
y = encoder.fit_transform(y_)

# Convert sparse tensor to dense tensor
y = y.toarray().squeeze()

print(f"on a y apres  one hot encoding : {y}")

on a y apres  one hot encoding : [[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1.

In [18]:
# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

In [19]:
# Build the model
model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ' + str(model.summary()))

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 fc1 (Dense)                 (None, 10)                50        
                                                                 
 fc2 (Dense)                 (None, 10)                110       
                                                                 
 output (Dense)              (None, 3)                 33        
                                                                 
Total params: 193 (772.00 Byte)
Trainable params: 193 (772.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Neural Network Model Summary: None


In [20]:
# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=500)

Epoch 1/500
24/24 - 3s - loss: 1.0483 - accuracy: 0.3917 - 3s/epoch - 119ms/step
Epoch 2/500
24/24 - 0s - loss: 0.9761 - accuracy: 0.6667 - 54ms/epoch - 2ms/step
Epoch 3/500
24/24 - 0s - loss: 0.9264 - accuracy: 0.6667 - 59ms/epoch - 2ms/step
Epoch 4/500
24/24 - 0s - loss: 0.8836 - accuracy: 0.6667 - 64ms/epoch - 3ms/step
Epoch 5/500
24/24 - 0s - loss: 0.8436 - accuracy: 0.6667 - 61ms/epoch - 3ms/step
Epoch 6/500
24/24 - 0s - loss: 0.7974 - accuracy: 0.6667 - 62ms/epoch - 3ms/step
Epoch 7/500
24/24 - 0s - loss: 0.7516 - accuracy: 0.6667 - 57ms/epoch - 2ms/step
Epoch 8/500
24/24 - 0s - loss: 0.7094 - accuracy: 0.6667 - 54ms/epoch - 2ms/step
Epoch 9/500
24/24 - 0s - loss: 0.6675 - accuracy: 0.6667 - 80ms/epoch - 3ms/step
Epoch 10/500
24/24 - 0s - loss: 0.6260 - accuracy: 0.6667 - 78ms/epoch - 3ms/step
Epoch 11/500
24/24 - 0s - loss: 0.5926 - accuracy: 0.7083 - 66ms/epoch - 3ms/step
Epoch 12/500
24/24 - 0s - loss: 0.5606 - accuracy: 0.6667 - 60ms/epoch - 3ms/step
Epoch 13/500
24/24 - 0s -

In [21]:
# Test on unseen data
results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

1/1 [==============================] - 1s 571ms/step - loss: 0.0244 - accuracy: 1.0000
Final test set loss: 0.024421
Final test set accuracy: 1.000000


In [22]:
# Prédictions sur les données de test
predictions = model.predict(test_x)

# Convertir les prédictions en classes
predicted_classes = np.argmax(predictions, axis=1)

# Comparer les prédictions avec les classes réelles
print('Prédictions: ' + str(predicted_classes))
print('Classes réelles: ' + str(test_y))

1/1 [==============================] - 0s 136ms/step
Prédictions: [1 2 2 2 2 1 1 2 2 0 1 1 2 0 2 0 2 1 2 2 1 2 1 2 0 0 1 1 0 2]
Classes réelles: [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [23]:
# A quelle classe appartient le fleur avec les mesures suivants
#longueur du sépale : 5.4
#largeur des sépale : 3.9
#longueur du pétale : 1.3
#largeur du pétale  : 0.4


# Prétraiter les nouvelles données
new_data = np.array([[5.4, 3.9, 1.3, 0.4]])  # Assurez-vous que la forme est correcte

predictions = model.predict(new_data)

# Convertir les prédictions en classes
predicted_classes = np.argmax(predictions, axis=1)
print("La classe de cette fleur est :", predicted_classes)

1/1 [==============================] - 0s 167ms/step
La classe de cette fleur est : [0]
